import type { FocusArea, LenormandCard } from "./types";

export const FOCUS_AREAS: Array<{ id: FocusArea; label: string }> = [
  { id: "geral", label: "Geral" },
  { id: "amor", label: "Amor" },
  { id: "sentimentos", label: "Sentimentos" },
  { id: "trabalho", label: "Trabalho" },
  { id: "financeiro", label: "Financeiro" },
  { id: "energia", label: "Saúde/energia" },
  { id: "espiritual", label: "Espiritual" },
  { id: "conselho", label: "Conselho" },
];

function cardImage(id: number) {
  return `/assets/games/baralho-cigano/card-${id.toString().padStart(2, "0")}.png`;
}

export const CARD_BACK = "/assets/games/baralho-cigano/back.png";

export const LENORMAND_CARDS: LenormandCard[] = [
  {
    id: 1,
    name: "O Cavaleiro",
    slug: "cavaleiro",
    image: cardImage(1),
    keywords: ["notícia", "chegada", "movimento", "convite", "mensageiro"],
    essence: "Algo se aproxima: uma notícia, visita, convite ou impulso que tira a situação da inércia.",
    light: "Agilidade, contato, iniciativa, novidades e abertura de caminho.",
    shadow: "Pressa, ansiedade, promessa sem base ou pessoa que passa rápido demais.",
    advice: "Responda ao chamado, mas confirme detalhes antes de correr.",
    timing: "Rápido; dias ou poucas semanas, dependendo das cartas vizinhas.",
    yesNo: "Sim",
    areas: {
      geral: "Indica movimento claro: uma mensagem, visita, proposta ou pessoa nova muda o ritmo da questão.",
      amor: "Pode trazer encontro, flerte, reconciliação por mensagem ou alguém tomando atitude.",
      sentimentos: "Mostra curiosidade, desejo de aproximação e vontade de testar a conexão.",
      trabalho: "Aponta chamada, entrevista, cliente, entrega, deslocamento ou resposta que chega.",
      financeiro: "Dinheiro em circulação, pagamento chegando ou oportunidade que pede ação rápida.",
      energia: "Energia acelerada; bom para se mexer, mas evite agir no impulso em temas de saúde.",
      espiritual: "Sinais aparecem por sincronicidade, recado, sonho curto ou conversa inesperada.",
      conselho: "Vá até a informação, responda contatos e dê o primeiro passo com objetividade.",
    },
    combinations: ["Com A Carta reforça mensagem formal.", "Com Os Caminhos indica decisão chegando.", "Com As Nuvens pede checar a clareza do recado."],
  },
  {
    id: 2,
    name: "O Trevo",
    slug: "trevo",
    image: cardImage(2),
    keywords: ["sorte", "chance", "leveza", "brevidade", "alívio"],
    essence: "Uma abertura simples surge e melhora o clima, mas precisa ser aproveitada enquanto está disponível.",
    light: "Sorte pequena, humor, solução rápida, oportunidade leve.",
    shadow: "Superficialidade, instabilidade, contar só com sorte ou deixar a chance passar.",
    advice: "Aproveite o intervalo favorável sem transformar tudo em aposta.",
    timing: "Muito rápido; horas, dias ou janela curta.",
    yesNo: "Sim",
    areas: {
      geral: "Mostra alívio, sorte pontual e uma solução menor que destrava parte do problema.",
      amor: "Favorece paquera, encontro descontraído e reaproximação sem pressão.",
      sentimentos: "A pessoa sente leveza, simpatia e curiosidade, mas ainda pode ser algo instável.",
      trabalho: "Pequena oportunidade, ajuda de última hora ou tarefa que sai melhor que o esperado.",
      financeiro: "Ganho pequeno, desconto, sorte em compra ou chance de economizar.",
      energia: "Bom sinal de recuperação leve e melhora de ânimo; cuide para não negligenciar rotina.",
      espiritual: "Proteção simples e sinais sutis mostrando que a porta não está fechada.",
      conselho: "Pegue a chance agora, resolva o simples primeiro e não complique o que está leve.",
    },
    combinations: ["Com O Sol amplia sorte e visibilidade.", "Com Os Ratos alerta para sorte desperdiçada.", "Com A Foice indica chance repentina."],
  },
  {
    id: 3,
    name: "O Navio",
    slug: "navio",
    image: cardImage(3),
    keywords: ["viagem", "distância", "comércio", "mudança", "horizonte"],
    essence: "A situação se desloca para longe do ponto atual, pedindo visão ampla, planejamento e travessia.",
    light: "Expansão, viagem, importação, aprendizado, aventura e negociação.",
    shadow: "Distância emocional, demora, fuga ou promessa que fica no horizonte.",
    advice: "Planeje a travessia e aceite que o resultado pode vir por etapas.",
    timing: "Médio prazo; semanas ou meses, especialmente com cartas lentas.",
    yesNo: "Sim",
    areas: {
      geral: "Fala de deslocamento, viagem, mudança de rota ou assunto envolvendo distância.",
      amor: "Pode indicar relacionamento à distância, saudade, viagem a dois ou vontade de explorar algo novo.",
      sentimentos: "Mostra desejo, imaginação e busca por algo maior, mas com certa distância emocional.",
      trabalho: "Favorece comércio, logística, clientes de fora, estudos e projetos internacionais.",
      financeiro: "Dinheiro ligado a vendas, transporte, importação, exportação ou investimentos de longo caminho.",
      energia: "Pede ritmo constante e descanso em viagens; não force o corpo em transições longas.",
      espiritual: "Expansão de consciência, busca por novos sistemas e chamado para sair do conhecido.",
      conselho: "Olhe além do imediato, organize recursos e aceite a fase de percurso.",
    },
    combinations: ["Com A Casa sugere mudança residencial.", "Com Os Peixes favorece comércio e fluxo financeiro.", "Com A Âncora indica viagem ou projeto de longo prazo."],
  },
  {
    id: 4,
    name: "A Casa",
    slug: "casa",
    image: cardImage(4),
    keywords: ["lar", "família", "base", "segurança", "privado"],
    essence: "A base da questão está na segurança, na vida privada, na família ou na estrutura que sustenta tudo.",
    light: "Proteção, estabilidade, pertencimento, rotina e acolhimento.",
    shadow: "Acomodação, isolamento, apego familiar ou medo de sair do lugar.",
    advice: "Fortaleça a base antes de buscar expansão.",
    timing: "Estável; costuma apontar continuidade ou processos domésticos.",
    yesNo: "Sim",
    areas: {
      geral: "Traz foco para lar, família, estrutura, proteção e assuntos íntimos.",
      amor: "Indica vínculo doméstico, desejo de construir vida juntos ou necessidade de segurança afetiva.",
      sentimentos: "A pessoa busca confiança, conforto e familiaridade; pode agir com cautela.",
      trabalho: "Favorece home office, negócio familiar, imóveis, hospedagem e atividades de base.",
      financeiro: "Gastos ou ganhos ligados a casa, família, aluguel, reforma ou patrimônio.",
      energia: "Rotina, sono e ambiente doméstico influenciam muito o bem-estar.",
      espiritual: "Proteção ancestral, altar doméstico, limpeza da casa e cuidado com o campo familiar.",
      conselho: "Organize o ambiente, proteja sua privacidade e resolva o que sustenta a situação.",
    },
    combinations: ["Com A Árvore fala de raízes familiares.", "Com A Torre pode indicar imóvel ou instituição.", "Com Os Ratos alerta desgaste no lar."],
  },
  {
    id: 5,
    name: "A Árvore",
    slug: "arvore",
    image: cardImage(5),
    keywords: ["saúde", "raízes", "crescimento", "tempo", "vitalidade"],
    essence: "Tudo cresce por raízes, tempo e constância; o tema pede maturação, cura e sustentação.",
    light: "Vitalidade, paciência, recuperação, conexão e evolução gradual.",
    shadow: "Lentidão, padrão antigo, enraizamento excessivo ou problema crônico.",
    advice: "Cuide da raiz e respeite o ritmo natural do processo.",
    timing: "Lento e orgânico; meses, estações ou ciclos de recuperação.",
    yesNo: "Sim",
    areas: {
      geral: "Mostra crescimento gradual, saúde, histórico, raízes e algo que precisa de tempo.",
      amor: "Relação que pode criar raízes, curar feridas e amadurecer sem pressa.",
      sentimentos: "Sentimentos profundos, constantes e ligados a memórias ou vínculo antigo.",
      trabalho: "Carreira construída com experiência, estabilidade e desenvolvimento de longo prazo.",
      financeiro: "Investimento lento, reserva, patrimônio e dinheiro que cresce com disciplina.",
      energia: "Carta central para vitalidade; observe hábitos e procure orientação profissional quando necessário.",
      espiritual: "Ancestralidade, natureza, aterramento, cura energética e conexão com ciclos.",
      conselho: "Pare de puxar a planta pelo caule: nutra, acompanhe e dê tempo.",
    },
    combinations: ["Com Os Lírios reforça cura e maturidade.", "Com O Caixão pode marcar encerramento de ciclo de saúde ou padrão.", "Com A Casa fala de linhagem e raízes familiares."],
  },
  {
    id: 6,
    name: "As Nuvens",
    slug: "nuvens",
    image: cardImage(6),
    keywords: ["confusão", "dúvida", "instabilidade", "névoa", "ambiguidade"],
    essence: "A visão ainda está turva; há mistura de medo, falta de informação e sinais contraditórios.",
    light: "Pausa para clarear, percepção de risco e chance de esperar a poeira baixar.",
    shadow: "Confusão, ansiedade, mentira parcial, clima pesado e decisão tomada no escuro.",
    advice: "Não conclua antes de checar fatos e aguardar a clareza.",
    timing: "Oscilante; melhora quando cartas claras aparecem depois.",
    yesNo: "Talvez",
    areas: {
      geral: "Indica falta de clareza, informação incompleta, dúvida ou ambiente instável.",
      amor: "Pode mostrar insegurança, mal-entendido, relação indefinida ou sinais mistos.",
      sentimentos: "Sentimentos confusos, medo de escolher e oscilação entre aproximação e recuo.",
      trabalho: "Reunião nebulosa, instrução mal passada, instabilidade ou política interna difícil de ler.",
      financeiro: "Evite apostas; há risco de conta escondida, preço pouco claro ou decisão precipitada.",
      energia: "Atenção a estresse mental e cansaço; não use a carta como diagnóstico.",
      espiritual: "Campo carregado, intuição misturada com medo e necessidade de limpeza e silêncio.",
      conselho: "Espere a névoa abrir, peça dados objetivos e não alimente paranoia.",
    },
    combinations: ["Com O Sol mostra clareza depois da confusão.", "Com A Cobra alerta para manipulação.", "Com A Carta pede ler contratos com atenção."],
  },
  {
    id: 7,
    name: "A Cobra",
    slug: "cobra",
    image: cardImage(7),
    keywords: ["estratégia", "sedução", "rivalidade", "desvio", "cuidado"],
    essence: "Há inteligência estratégica, desejo e possível complicação; avance com percepção fina.",
    light: "Astúcia, magnetismo, proteção, leitura de riscos e negociação habilidosa.",
    shadow: "Ciúme, intriga, traição, inveja, manipulação ou caminho tortuoso.",
    advice: "Observe intenções e não entregue tudo de primeira.",
    timing: "Processo sinuoso; pode atrasar por desvios.",
    yesNo: "Depende",
    areas: {
      geral: "Mostra situação complexa, rivalidade, desejo oculto ou caminho que exige estratégia.",
      amor: "Pode indicar paixão intensa, triângulo, ciúme ou pessoa sedutora e difícil de ler.",
      sentimentos: "Sentimentos misturam atração, posse, medo de perder e cálculo emocional.",
      trabalho: "Atenção a concorrência, bastidores, negociação sensível e pessoas ambiciosas.",
      financeiro: "Cuidado com propostas bonitas demais, dívida enrolada ou disputa por recursos.",
      energia: "Tensão acumulada e somatização podem pesar; procure apoio adequado se houver sintoma.",
      espiritual: "Proteção, transmutação e leitura de inveja ou energia densa ao redor.",
      conselho: "Seja elegante, estratégico e discreto; confie em ações, não só em discurso.",
    },
    combinations: ["Com O Coração fala de paixão complicada.", "Com A Raposa reforça alerta de interesse oculto.", "Com Os Lírios pode transformar desejo em maturidade."],
  },
  {
    id: 8,
    name: "O Caixão",
    slug: "caixao",
    image: cardImage(8),
    keywords: ["fim", "luto", "encerramento", "pausa", "transformação"],
    essence: "Um ciclo se fecha ou precisa ser encerrado para que outra forma de vida possa surgir.",
    light: "Liberação, conclusão, descanso, transformação e fim de desgaste.",
    shadow: "Perda, bloqueio emocional, apego ao que acabou ou medo de mudança.",
    advice: "Aceite o fim real e não prolongue o que já cumpriu sua função.",
    timing: "Marca fechamento; o tempo depende da aceitação do encerramento.",
    yesNo: "Não",
    areas: {
      geral: "Indica conclusão, corte de ciclo, esgotamento ou necessidade de parar algo.",
      amor: "Pode mostrar término, distanciamento ou fim de uma fase para renascer de outro jeito.",
      sentimentos: "Sentimentos recolhidos, tristeza, fechamento e dificuldade de reagir.",
      trabalho: "Fim de projeto, desligamento, pausa obrigatória ou encerramento de função.",
      financeiro: "Cortar gastos, fechar dívida, encerrar investimento ruim ou lidar com perda.",
      energia: "Pede descanso e cuidado com exaustão; avaliação profissional é essencial em saúde.",
      espiritual: "Desapego, luto simbólico, trabalho de ancestralidade e transformação profunda.",
      conselho: "Dê nome ao fim, retire energia do que morreu e preserve o que ainda tem vida.",
    },
    combinations: ["Com A Foice reforça corte definitivo.", "Com A Cegonha indica transformação depois do fim.", "Com O Sol mostra recuperação após fase pesada."],
  },
  {
    id: 9,
    name: "O Buquê",
    slug: "buque",
    image: cardImage(9),
    keywords: ["presente", "alegria", "convite", "beleza", "gratidão"],
    essence: "A vida oferece um agrado, reconhecimento ou gesto bonito que suaviza a situação.",
    light: "Gentileza, charme, celebração, convite, reconciliação e prazer.",
    shadow: "Aparência sem profundidade, agrado interesseiro ou evitar conflito com sorriso.",
    advice: "Receba o que vem de bom e também expresse gratidão.",
    timing: "Breve e agradável; costuma ser rápido.",
    yesNo: "Sim",
    areas: {
      geral: "Traz surpresa positiva, convite, elogio, presente ou clima de celebração.",
      amor: "Favorece romantismo, pedido de encontro, carinho, reconciliação e demonstração afetuosa.",
      sentimentos: "Mostra admiração, encanto, prazer e vontade de agradar.",
      trabalho: "Reconhecimento, bom atendimento, networking simpático ou proposta agradável.",
      financeiro: "Pequeno ganho, benefício, mimo, bônus ou dinheiro ligado a beleza e eventos.",
      energia: "Bem-estar melhora com prazer, descanso e ambiente bonito; não substitui cuidado médico.",
      espiritual: "Gratidão, oferenda simbólica, beleza como cura e abertura do coração.",
      conselho: "Seja receptivo, use diplomacia e valorize gestos simples.",
    },
    combinations: ["Com O Anel favorece compromisso feliz.", "Com O Jardim indica convite social.", "Com A Cobra pede checar se o agrado tem intenção oculta."],
  },
  {
    id: 10,
    name: "A Foice",
    slug: "foice",
    image: cardImage(10),
    keywords: ["corte", "decisão", "urgência", "ruptura", "colheita"],
    essence: "Algo precisa ser cortado, decidido ou colhido de forma direta; a energia é rápida e sem rodeio.",
    light: "Decisão, limpeza, precisão, colheita e fim de indecisão.",
    shadow: "Impulsividade, acidente, fala cortante, ruptura brusca ou perda por pressa.",
    advice: "Corte com consciência: rápido não precisa ser destrutivo.",
    timing: "Imediato; eventos súbitos ou decisão urgente.",
    yesNo: "Não",
    areas: {
      geral: "Indica corte rápido, decisão inevitável, ruptura ou separação de algo.",
      amor: "Pode mostrar término, conversa dura ou necessidade de cortar dinâmica repetida.",
      sentimentos: "A pessoa pode estar defensiva, seca, assustada ou pronta para decidir.",
      trabalho: "Prazo urgente, demissão, mudança brusca, ferramenta afiada ou decisão gerencial.",
      financeiro: "Corte de gastos, perda repentina ou necessidade de agir para preservar dinheiro.",
      energia: "Atenção a acidentes, tensão e impulsos; em saúde, busque avaliação adequada.",
      espiritual: "Limpeza energética, banimento, quebra de padrão e corte de vínculos desgastantes.",
      conselho: "Faça o necessário agora, mas evite ferir por falta de calma.",
    },
    combinations: ["Com O Caixão fecha ciclo de vez.", "Com O Trevo indica chance repentina.", "Com A Carta mostra documento de corte ou aviso."],
  },
  {
    id: 11,
    name: "O Chicote",
    slug: "chicote",
    image: cardImage(11),
    keywords: ["conflito", "repetição", "discussão", "disciplina", "tensão"],
    essence: "O tema se repete e esquenta: há debate, cobrança, culpa, disciplina ou padrão de atrito.",
    light: "Treino, persistência, debate produtivo e energia para romper repetição.",
    shadow: "Briga, agressividade, ciclo vicioso, autocobrança e desgaste verbal.",
    advice: "Interrompa a repetição antes que ela vire punição.",
    timing: "Recorrente; algo volta várias vezes até ser tratado.",
    yesNo: "Não",
    areas: {
      geral: "Mostra conflito, discussão, cobrança ou padrão que se repete.",
      amor: "Indica brigas recorrentes, química intensa, ciúmes ou relação com altos e baixos.",
      sentimentos: "Sentimentos tensos, irritação, culpa ou desejo misturado com conflito.",
      trabalho: "Ambiente competitivo, cobrança dura, retrabalho, treinamento ou disputa verbal.",
      financeiro: "Gastos repetidos, multa, cobrança ou dívida que volta a incomodar.",
      energia: "Tensão, irritabilidade e excesso de cobrança drenam; cuide de corpo e limites.",
      espiritual: "Padrão kármico, limpeza de repetição e necessidade de quebrar ciclo energético.",
      conselho: "Nomeie o ciclo, baixe o tom e coloque limite claro.",
    },
    combinations: ["Com Os Pássaros aumenta ansiedade e discussão.", "Com A Cobra sugere intriga repetida.", "Com A Âncora indica padrão antigo difícil de mover."],
  },
  {
    id: 12,
    name: "Os Pássaros",
    slug: "passaros",
    image: cardImage(12),
    keywords: ["conversa", "dupla", "ansiedade", "troca", "agitação"],
    essence: "A situação passa por conversa, troca rápida, ruído mental ou duas pessoas influenciando o tema.",
    light: "Diálogo, chamada, parceria, socialização e troca de ideias.",
    shadow: "Fofoca, nervosismo, barulho, indecisão e fala sem profundidade.",
    advice: "Converse, mas filtre ruído e ansiedade.",
    timing: "Rápido e oscilante; contatos no mesmo dia ou semana.",
    yesNo: "Talvez",
    areas: {
      geral: "Indica conversa, telefonema, reunião curta, ansiedade ou assunto compartilhado.",
      amor: "Mostra troca de mensagens, casal conversando ou necessidade de alinhar expectativas.",
      sentimentos: "A pessoa pensa muito, fala com alguém sobre você e pode estar nervosa.",
      trabalho: "Reuniões, atendimento, comunicação, dupla de trabalho ou excesso de demandas simultâneas.",
      financeiro: "Negociação, cobrança conversada, ajuste pequeno ou ansiedade sobre contas.",
      energia: "Sistema nervoso sobrecarregado; reduza estímulos e procure ajuda se a ansiedade apertar.",
      espiritual: "Mensagens sutis por sons, aves, conversa repetida ou intuição em pares.",
      conselho: "Fale o essencial, escute com calma e não transforme hipótese em fato.",
    },
    combinations: ["Com A Carta reforça mensagem escrita.", "Com O Chicote vira discussão repetida.", "Com O Jardim aponta reunião social."],
  },
  {
    id: 13,
    name: "A Criança",
    slug: "crianca",
    image: cardImage(13),
    keywords: ["começo", "inocência", "pequeno", "filhos", "novidade"],
    essence: "Algo nasce pequeno e ainda precisa de cuidado, aprendizado e proteção.",
    light: "Novo começo, espontaneidade, leveza, criatividade e simplicidade.",
    shadow: "Imaturidade, ingenuidade, pouca experiência ou minimizar tema importante.",
    advice: "Comece simples e cuide do início com paciência.",
    timing: "Início recente; algo novo ou pequeno.",
    yesNo: "Sim",
    areas: {
      geral: "Mostra começo, novidade, criança literal, assunto pequeno ou fase inicial.",
      amor: "Pode indicar relação nova, leve, inocente ou necessidade de amadurecer o vínculo.",
      sentimentos: "Sentimentos nascendo, curiosidade, timidez e medo de se expor demais.",
      trabalho: "Projeto piloto, aprendizado, estágio, função nova ou ideia criativa ainda pequena.",
      financeiro: "Ganho inicial, reserva pequena, primeiro passo ou cuidado com ingenuidade em compras.",
      energia: "Renovação leve; cuide de sono, rotina e sinais básicos sem dramatizar.",
      espiritual: "Reconexão com criança interior, pureza, começo de prática e confiança simples.",
      conselho: "Não pule etapas; proteja o início até ele ganhar corpo.",
    },
    combinations: ["Com A Cegonha pode falar de gravidez ou novidade familiar.", "Com O Livro indica aprendizado.", "Com O Urso pede proteção de alguém vulnerável."],
  },
  {
    id: 14,
    name: "A Raposa",
    slug: "raposa",
    image: cardImage(14),
    keywords: ["cautela", "trabalho", "astúcia", "autoproteção", "interesse"],
    essence: "A situação pede inteligência prática, leitura de intenções e cuidado com interesse escondido.",
    light: "Estratégia, adaptação, autonomia, foco profissional e sobrevivência.",
    shadow: "Engano, exploração, falsa promessa, desconfiança ou pessoa agindo por vantagem.",
    advice: "Verifique o que cada um ganha com a situação.",
    timing: "Variável; depende de estratégia e observação.",
    yesNo: "Depende",
    areas: {
      geral: "Alerta para cautela, interesse oculto, estratégia ou necessidade de se proteger.",
      amor: "Pode mostrar alguém evitando compromisso, agindo por conveniência ou testando limites.",
      sentimentos: "Sentimentos contidos por medo, cálculo, autoproteção ou desconfiança.",
      trabalho: "Carta forte para emprego, rotina profissional, chefe esperto e política de escritório.",
      financeiro: "Revise contrato, comissão, proposta informal e ganhos que dependem de esperteza.",
      energia: "Não ignore sinais do corpo por produtividade; cuidado com esgotamento por trabalho.",
      espiritual: "Discernimento, proteção contra engano e leitura do que parece bonito mas não sustenta.",
      conselho: "Seja esperto sem perder ética; confirme dados e proteja seu espaço.",
    },
    combinations: ["Com A Cobra aumenta risco de manipulação.", "Com O Livro fala de informação escondida.", "Com O Urso pode indicar chefe ou poder estratégico."],
  },
  {
    id: 15,
    name: "O Urso",
    slug: "urso",
    image: cardImage(15),
    keywords: ["poder", "proteção", "força", "chefia", "posse"],
    essence: "Há força, autoridade e proteção, mas também peso, controle ou domínio de alguém influente.",
    light: "Segurança, coragem, liderança, prosperidade e defesa.",
    shadow: "Ciúme, controle, possessividade, autoritarismo ou excesso.",
    advice: "Use força para proteger, não para sufocar.",
    timing: "Lento e pesado; envolve consolidação.",
    yesNo: "Sim",
    areas: {
      geral: "Mostra pessoa forte, chefe, protetor, mãe/pai dominante ou tema de poder.",
      amor: "Pode indicar amor protetor, ciúme, intensidade física ou dinâmica de controle.",
      sentimentos: "Sentimentos fortes, possessivos e cuidadosos, com medo de perder território.",
      trabalho: "Chefia, liderança, autoridade, recursos, cargo alto ou disputa por influência.",
      financeiro: "Potencial de ganho alto, patrimônio e força material, mas cuidado com excessos.",
      energia: "Força vital e resistência; atenção a excessos, peso e tensão corporal.",
      espiritual: "Animal de poder, proteção firme, guardião e trabalho de força interior.",
      conselho: "Assuma autoridade com maturidade e defina limites de poder.",
    },
    combinations: ["Com Os Peixes reforça dinheiro e poder material.", "Com A Casa indica proteção familiar.", "Com A Cobra pode virar ciúme e controle."],
  },
  {
    id: 16,
    name: "As Estrelas",
    slug: "estrelas",
    image: cardImage(16),
    keywords: ["esperança", "guia", "internet", "inspiração", "propósito"],
    essence: "A visão se abre para esperança, orientação, propósito e conexão com algo maior.",
    light: "Inspiração, fé, visibilidade, tecnologia, sonhos e cura espiritual.",
    shadow: "Idealização, dispersão, promessa distante ou viver só de expectativa.",
    advice: "Siga o norte, mas transforme inspiração em rota prática.",
    timing: "Futuro promissor; pode indicar noite, internet ou médio prazo.",
    yesNo: "Sim",
    areas: {
      geral: "Traz esperança, direção, sonho, internet, exposição positiva e proteção sutil.",
      amor: "Mostra idealização, conexão espiritual, esperança de reconciliação ou relação inspiradora.",
      sentimentos: "Sentimentos elevados, admiração e vontade de acreditar no futuro.",
      trabalho: "Favorece tecnologia, redes, marketing, criatividade, reputação e planejamento de longo alcance.",
      financeiro: "Boa perspectiva, ganhos por internet ou projeto escalável, com cuidado contra fantasia.",
      energia: "Ânimo e recuperação energética; combine fé com cuidados concretos.",
      espiritual: "Carta de guia, proteção espiritual, sonhos importantes e conexão com propósito.",
      conselho: "Escolha uma estrela-guia e aja de acordo com ela todos os dias.",
    },
    combinations: ["Com A Chave indica solução inspirada.", "Com A Lua reforça intuição e reconhecimento.", "Com As Nuvens mostra esperança ainda confusa."],
  },
  {
    id: 17,
    name: "A Cegonha",
    slug: "cegonha",
    image: cardImage(17),
    keywords: ["mudança", "renovação", "gravidez", "melhoria", "transição"],
    essence: "A fase muda de lugar: algo se renova, melhora, chega ou pede adaptação.",
    light: "Progresso, novidade, mudança positiva, chegada e atualização.",
    shadow: "Instabilidade, mudança precipitada, repetição de ciclos ou expectativa sem preparo.",
    advice: "Ajuste o ninho antes da chegada da novidade.",
    timing: "Próximo ciclo; semanas ou meses, muitas vezes ligado a mudança de fase.",
    yesNo: "Sim",
    areas: {
      geral: "Indica mudança, melhoria, novidade, gravidez possível ou transição de fase.",
      amor: "Relação muda de nível, volta com nova postura ou abre chance para família.",
      sentimentos: "Sentimentos em transformação, vontade de melhorar e sair do padrão antigo.",
      trabalho: "Mudança de função, emprego, rotina, equipe ou formato de projeto.",
      financeiro: "Ajustes de renda, mudança de orçamento ou dinheiro ligado a uma nova etapa.",
      energia: "Renovação de hábitos e adaptação do corpo; em gravidez/saúde, busque confirmação médica.",
      espiritual: "Transição energética, renascimento e sinais de que uma fase se desloca.",
      conselho: "Prepare-se para mudar com método, não só com entusiasmo.",
    },
    combinations: ["Com A Criança pode falar de nascimento literal ou simbólico.", "Com A Casa sugere mudança de casa.", "Com O Caixão indica transformação profunda."],
  },
  {
    id: 18,
    name: "O Cachorro",
    slug: "cachorro",
    image: cardImage(18),
    keywords: ["amizade", "lealdade", "apoio", "confiança", "companheirismo"],
    essence: "A resposta passa por lealdade, amizade, apoio confiável e vínculo que se mostra nas atitudes.",
    light: "Fidelidade, parceria, ajuda, confiança e presença constante.",
    shadow: "Dependência, zona de amizade, submissão ou confiar sem avaliar reciprocidade.",
    advice: "Valorize quem aparece de forma consistente.",
    timing: "Constante; tende a permanecer.",
    yesNo: "Sim",
    areas: {
      geral: "Mostra amigo, aliado, apoio fiel ou situação que depende de confiança.",
      amor: "Pode indicar companheirismo, relação amiga, fidelidade ou alguém que quer estar perto.",
      sentimentos: "Sentimentos leais, cuidadosos e presentes, ainda que nem sempre passionais.",
      trabalho: "Colega confiável, parceria, equipe leal ou cliente recorrente.",
      financeiro: "Apoio de alguém, parceria estável ou ganho por serviço de confiança.",
      energia: "Apoio emocional ajuda o bem-estar; companhia e rotina reduzem peso mental.",
      espiritual: "Guias próximos, proteção amiga e sinais por animais ou companheiros fiéis.",
      conselho: "Conte com aliados reais e seja leal sem se anular.",
    },
    combinations: ["Com O Coração mostra amor amigo e fiel.", "Com A Raposa alerta para falso amigo.", "Com O Anel favorece parceria estável."],
  },
  {
    id: 19,
    name: "A Torre",
    slug: "torre",
    image: cardImage(19),
    keywords: ["instituição", "isolamento", "autoridade", "estrutura", "limites"],
    essence: "A questão envolve instituição, regras, distância, limites formais ou posição solitária.",
    light: "Autonomia, proteção legal, estrutura, disciplina e visão de cima.",
    shadow: "Frieza, burocracia, solidão, rigidez ou autoridade distante.",
    advice: "Respeite regras e limites; se isole só o suficiente para pensar.",
    timing: "Lento e institucional; depende de processo formal.",
    yesNo: "Depende",
    areas: {
      geral: "Fala de órgão público, empresa grande, hospital, escola, justiça, isolamento ou limite formal.",
      amor: "Mostra distância emocional, relação formal, necessidade de limites ou fase de solidão.",
      sentimentos: "Sentimentos contidos, postura defensiva e dificuldade de demonstrar vulnerabilidade.",
      trabalho: "Empresa, hierarquia, carreira pública, compliance, documentação e burocracia.",
      financeiro: "Banco, imposto, previdência, contrato institucional ou dinheiro preso por regra.",
      energia: "Pode apontar instituições de saúde e necessidade de acompanhamento formal.",
      espiritual: "Retiro, disciplina espiritual, proteção por limites e estudo estruturado.",
      conselho: "Formalize, respeite protocolos e não force intimidade onde há barreira legítima.",
    },
    combinations: ["Com A Carta indica documento oficial.", "Com A Casa pode falar de prédio ou imóvel.", "Com O Jardim mostra instituição pública ou evento formal."],
  },
  {
    id: 20,
    name: "O Jardim",
    slug: "jardim",
    image: cardImage(20),
    keywords: ["público", "rede", "evento", "social", "exposição"],
    essence: "A situação se abre ao público, à rede social, comunidade, encontro ou ambiente coletivo.",
    light: "Networking, visibilidade, celebração, comunidade e oportunidades sociais.",
    shadow: "Opinião alheia, superficialidade social, exposição excessiva ou fofoca pública.",
    advice: "Circule, mas escolha bem onde se expõe.",
    timing: "Datas marcadas, eventos e encontros.",
    yesNo: "Sim",
    areas: {
      geral: "Indica evento, rede social, reunião, público, comunidade ou algo visto por outras pessoas.",
      amor: "Favorece encontros sociais, conhecer alguém em evento ou assumir algo publicamente.",
      sentimentos: "A pessoa observa socialmente, quer interagir e pode se importar com imagem pública.",
      trabalho: "Networking, reunião ampla, audiência, marketing, palestra e comunidade profissional.",
      financeiro: "Ganhos por público, eventos, vendas presenciais ou influência de rede.",
      energia: "Ambiente social pode energizar ou cansar; ajuste exposição conforme seu limite.",
      espiritual: "Círculo espiritual, grupo, ritual coletivo ou aprendizado em comunidade.",
      conselho: "Apareça no lugar certo, fale com pessoas e cuide da reputação.",
    },
    combinations: ["Com O Buquê indica convite agradável.", "Com Os Pássaros mostra reunião ou conversa pública.", "Com A Lua reforça reconhecimento social."],
  },
  {
    id: 21,
    name: "A Montanha",
    slug: "montanha",
    image: cardImage(21),
    keywords: ["obstáculo", "bloqueio", "distância", "desafio", "resistência"],
    essence: "Há um obstáculo real no caminho; a resposta exige paciência, estratégia e força de subida.",
    light: "Persistência, maturidade, proteção por barreira e conquista difícil.",
    shadow: "Bloqueio, frieza, demora, impossibilidade momentânea e solidão.",
    advice: "Não empurre a montanha; encontre rota, tempo ou ferramenta.",
    timing: "Lento; atrasos e espera.",
    yesNo: "Não",
    areas: {
      geral: "Mostra bloqueio, atraso, distância, barreira externa ou dificuldade objetiva.",
      amor: "Indica frieza, distância, obstáculo para encontro ou relação que não flui agora.",
      sentimentos: "Sentimentos bloqueados, defesa emocional e dificuldade de se abrir.",
      trabalho: "Projeto travado, aprovação difícil, concorrência pesada ou meta alta.",
      financeiro: "Dinheiro bloqueado, atraso de pagamento, dívida difícil ou restrição de crédito.",
      energia: "Cansaço por resistência prolongada; respeite limites e procure suporte quando necessário.",
      espiritual: "Prova de paciência, isolamento produtivo e aprendizado por perseverança.",
      conselho: "Mapeie o obstáculo, escolha uma rota realista e não confunda demora com derrota.",
    },
    combinations: ["Com A Chave mostra solução para bloqueio.", "Com Os Caminhos aponta rota alternativa.", "Com O Sol indica superação."],
  },
  {
    id: 22,
    name: "Os Caminhos",
    slug: "caminhos",
    image: cardImage(22),
    keywords: ["escolha", "alternativa", "livre-arbítrio", "bifurcação", "opção"],
    essence: "A pergunta está em uma bifurcação: há escolha, rota alternativa e responsabilidade pela direção.",
    light: "Liberdade, estratégia, possibilidades e ajuste de rota.",
    shadow: "Indecisão, dispersão, fuga de compromisso ou adiar escolha.",
    advice: "Escolha com critérios, não por medo de perder todas as opções.",
    timing: "Depende da decisão; acelera quando uma rota é assumida.",
    yesNo: "Depende",
    areas: {
      geral: "Mostra decisão, duas opções, rota alternativa ou momento de escolher direção.",
      amor: "Pode indicar triângulo, escolha afetiva, dúvida entre ficar ou sair, ou relação em aberto.",
      sentimentos: "Sentimentos divididos e necessidade de entender o que realmente se quer.",
      trabalho: "Mudança de carreira, duas propostas, escolha de estratégia ou bifurcação de projeto.",
      financeiro: "Comparar investimentos, renegociar rota, escolher prioridade ou evitar gasto duplicado.",
      energia: "Escolhas de rotina impactam o corpo; opte pelo caminho sustentável.",
      espiritual: "Livre-arbítrio em destaque; sinais mostram possibilidades, não sentença fixa.",
      conselho: "Liste critérios, elimine a opção que só existe por medo e caminhe.",
    },
    combinations: ["Com O Cavaleiro traz decisão após notícia.", "Com A Foice indica corte de uma opção.", "Com O Coração mostra escolha emocional."],
  },
  {
    id: 23,
    name: "Os Ratos",
    slug: "ratos",
    image: cardImage(23),
    keywords: ["perda", "desgaste", "ansiedade", "roubo", "erosão"],
    essence: "Algo está sendo consumido aos poucos: tempo, dinheiro, confiança, energia ou paz mental.",
    light: "Perceber vazamento, reduzir danos e limpar o que corrói.",
    shadow: "Perda, roubo, vício, desgaste, preocupação e deterioração lenta.",
    advice: "Feche vazamentos pequenos antes que virem rombo.",
    timing: "Gradual; desgaste acumulado.",
    yesNo: "Não",
    areas: {
      geral: "Indica perda, desgaste, ansiedade, roubo, falha ou algo sendo corroído aos poucos.",
      amor: "Mostra ciúme, insegurança, desgaste da relação ou confiança sendo consumida.",
      sentimentos: "Sentimentos ansiosos, medo de perder, culpa ou preocupação constante.",
      trabalho: "Retrabalho, perda de prazo, sabotagem, ambiente drenante ou falhas pequenas repetidas.",
      financeiro: "Vazamento de dinheiro, gasto oculto, juros, furto ou prejuízo por descuido.",
      energia: "Drenagem, insônia e estresse podem pesar; busque suporte se persistir.",
      espiritual: "Energia drenada, obsessão por problema e necessidade de limpeza e proteção.",
      conselho: "Audite o que está escapando: tempo, dinheiro, atenção e confiança.",
    },
    combinations: ["Com Os Peixes alerta perda financeira.", "Com A Casa mostra desgaste no lar.", "Com O Trevo indica chance desperdiçada."],
  },
  {
    id: 24,
    name: "O Coração",
    slug: "coracao",
    image: cardImage(24),
    keywords: ["amor", "afeto", "paixão", "prazer", "emoção"],
    essence: "O centro da questão é emocional: amor, desejo, alegria, compaixão ou aquilo que o coração escolhe.",
    light: "Amor, carinho, generosidade, paixão, prazer e abertura afetiva.",
    shadow: "Carência, idealização, apego, decisão só emocional ou coração sem limite.",
    advice: "Honre o sentimento sem abandonar discernimento.",
    timing: "Rápido quando há abertura; ligado a momentos emocionais.",
    yesNo: "Sim",
    areas: {
      geral: "Traz afeto, prazer, vínculo emocional, desejo ou algo que importa profundamente.",
      amor: "Carta forte de amor, paixão, romance, carinho e abertura para se conectar.",
      sentimentos: "Sentimentos presentes e vivos; a pessoa sente atração, ternura ou envolvimento.",
      trabalho: "Trabalho feito com prazer, propósito, criatividade ou relação cordial no ambiente.",
      financeiro: "Dinheiro gasto com prazer ou pessoas amadas; cuide para não comprar afeto.",
      energia: "Alegria e afeto melhoram a vitalidade; preserve limites emocionais.",
      espiritual: "Coração aberto, compaixão, cura emocional e práticas de amorosidade.",
      conselho: "Pergunte o que seu coração quer, depois veja como cuidar disso na prática.",
    },
    combinations: ["Com O Anel favorece compromisso amoroso.", "Com A Cobra mostra paixão complexa.", "Com Os Lírios indica amor maduro."],
  },
  {
    id: 25,
    name: "O Anel",
    slug: "anel",
    image: cardImage(25),
    keywords: ["compromisso", "contrato", "ciclo", "aliança", "vínculo"],
    essence: "Há acordo, repetição, aliança ou compromisso que une partes em um ciclo.",
    light: "Parceria, contrato, promessa, fidelidade e continuidade.",
    shadow: "Obrigação pesada, ciclo repetitivo, prisão por acordo ou promessa vazia.",
    advice: "Defina os termos antes de assumir o vínculo.",
    timing: "Cíclico; repete ou se firma por prazo.",
    yesNo: "Sim",
    areas: {
      geral: "Mostra compromisso, contrato, pacto, acordo, parceria ou ciclo recorrente.",
      amor: "Indica namoro, casamento, reconciliação com promessa ou vínculo que busca estabilidade.",
      sentimentos: "Sentimentos querem continuidade, exclusividade ou segurança de pertencimento.",
      trabalho: "Contrato, parceria comercial, renovação, cliente fixo ou vínculo profissional.",
      financeiro: "Acordo financeiro, assinatura, mensalidade, compromisso de pagamento ou investimento recorrente.",
      energia: "Rotina constante ajuda; cuidado com ciclos de hábito que prendem.",
      espiritual: "Pacto simbólico, compromisso com prática, promessa espiritual e ciclos repetidos.",
      conselho: "Não assuma só pela emoção; combine regras claras e revise obrigações.",
    },
    combinations: ["Com A Carta indica contrato escrito.", "Com O Coração mostra compromisso afetivo.", "Com Os Ratos alerta vínculo desgastante."],
  },
  {
    id: 26,
    name: "O Livro",
    slug: "livro",
    image: cardImage(26),
    keywords: ["segredo", "estudo", "conhecimento", "mistério", "registro"],
    essence: "Nem tudo está revelado; conhecimento, segredo, estudo ou documento fechado conduz a resposta.",
    light: "Aprendizado, pesquisa, sabedoria, especialização e descoberta.",
    shadow: "Segredo, ocultação, falta de transparência ou informação inacessível.",
    advice: "Pesquise antes de falar e proteja informações sensíveis.",
    timing: "Depende da revelação; pode demorar até a informação abrir.",
    yesNo: "Talvez",
    areas: {
      geral: "Indica segredo, estudo, informação guardada, prova, livro, arquivo ou conhecimento técnico.",
      amor: "Pode mostrar sentimento escondido, relação discreta ou algo que ainda não foi revelado.",
      sentimentos: "A pessoa guarda o que sente, observa e tenta entender antes de se abrir.",
      trabalho: "Estudos, certificação, documentos internos, pesquisa, tecnologia ou assunto confidencial.",
      financeiro: "Leia termos, impostos, extratos e dados ocultos antes de decidir.",
      energia: "Investigue causas com profissional; a carta aponta busca de informação, não diagnóstico.",
      espiritual: "Estudo oculto, tradição, mistério, diário espiritual e conhecimento reservado.",
      conselho: "Faça perguntas melhores, estude o caso e não exponha segredo sem necessidade.",
    },
    combinations: ["Com A Chave revela resposta importante.", "Com A Raposa alerta informação escondida por interesse.", "Com A Criança indica aprendizado novo."],
  },
  {
    id: 27,
    name: "A Carta",
    slug: "carta",
    image: cardImage(27),
    keywords: ["mensagem", "documento", "prova", "email", "notificação"],
    essence: "A resposta vem por escrito: mensagem, documento, convite, contrato, exame, recibo ou notificação.",
    light: "Comunicação objetiva, registro, convite e comprovação.",
    shadow: "Documento frio, mensagem ambígua, formalidade excessiva ou notícia que exige leitura cuidadosa.",
    advice: "Leia, registre e responda com clareza.",
    timing: "Rápido; chega por canal escrito.",
    yesNo: "Sim",
    areas: {
      geral: "Mostra mensagem, carta, email, contrato, comprovante, exame ou documento importante.",
      amor: "Indica mensagem afetiva, convite, explicação por texto ou conversa que começa no escrito.",
      sentimentos: "A pessoa pode demonstrar mais por mensagem do que pessoalmente.",
      trabalho: "Contrato, proposta, currículo, comunicado, relatório ou formalização.",
      financeiro: "Boleto, comprovante, nota, contrato, cobrança ou registro de pagamento.",
      energia: "Exames, laudos e orientações por escrito precisam ser lidos com profissional.",
      espiritual: "Mensagem simbólica, escrita intuitiva, bilhete, oração ou sinal registrado.",
      conselho: "Coloque no papel, revise detalhes e não aceite acordo só verbal.",
    },
    combinations: ["Com O Cavaleiro traz notícia chegando.", "Com O Anel indica contrato.", "Com As Nuvens pede atenção a texto confuso."],
  },
  {
    id: 28,
    name: "O Homem",
    slug: "homem",
    image: cardImage(28),
    keywords: ["consulente", "masculino", "parceiro", "ação", "referência"],
    essence: "Representa uma pessoa masculina, energia de ação ou o próprio consulente quando se identifica com essa figura.",
    light: "Presença, iniciativa, racionalidade, proteção e foco.",
    shadow: "Rigidez, orgulho, controle ou dificuldade de expressar emoção.",
    advice: "Observe ações concretas dessa pessoa ou energia.",
    timing: "Depende da pessoa representada.",
    yesNo: "Depende",
    areas: {
      geral: "Indica homem importante, consulente masculino, parceiro, pai, chefe ou energia ativa.",
      amor: "Pode representar parceiro, pretendente, ex, figura masculina ou postura ativa na relação.",
      sentimentos: "Sentimentos existem, mas podem aparecer por atitudes mais do que por palavras.",
      trabalho: "Chefe, colega, cliente masculino ou necessidade de assumir postura objetiva.",
      financeiro: "Recursos ligados a homem específico, decisão racional ou negociação direta.",
      energia: "Atenção à forma como força, cobrança e silêncio emocional afetam o corpo.",
      espiritual: "Arquétipo masculino, ação, proteção, ancestral masculino ou equilíbrio de polaridades.",
      conselho: "Analise a pessoa pelo que faz, não só pelo papel que ocupa.",
    },
    combinations: ["Com A Mulher destaca casal ou contraparte.", "Com O Coração indica interesse afetivo.", "Com A Torre mostra homem distante ou institucional."],
  },
  {
    id: 29,
    name: "A Mulher",
    slug: "mulher",
    image: cardImage(29),
    keywords: ["consulente", "feminino", "parceira", "receptividade", "referência"],
    essence: "Representa uma pessoa feminina, energia receptiva ou a própria consulente quando se identifica com essa figura.",
    light: "Intuição, presença, cuidado, magnetismo e percepção.",
    shadow: "Passividade, drama, controle sutil ou esperar sem se posicionar.",
    advice: "Observe a postura emocional e a forma de receber ou conduzir.",
    timing: "Depende da pessoa representada.",
    yesNo: "Depende",
    areas: {
      geral: "Indica mulher importante, consulente feminina, parceira, mãe, chefe ou energia receptiva.",
      amor: "Pode representar parceira, pretendente, ex, figura feminina ou a dinâmica emocional da relação.",
      sentimentos: "Sentimentos são percebidos por cuidado, presença, intuição e reação emocional.",
      trabalho: "Chefe, colega, cliente feminina ou necessidade de sensibilidade estratégica.",
      financeiro: "Recursos ligados a mulher específica, cuidado com gastos ou decisão intuitiva bem verificada.",
      energia: "Escute sinais internos e ritmos do corpo; busque orientação se houver sintoma.",
      espiritual: "Arquétipo feminino, intuição, ancestral feminina e força de acolhimento.",
      conselho: "Receba informações sem se calar: sentir e agir precisam caminhar juntos.",
    },
    combinations: ["Com O Homem destaca casal ou contraparte.", "Com A Lua aumenta intuição.", "Com A Cobra pode indicar rivalidade ou magnetismo feminino."],
  },
  {
    id: 30,
    name: "Os Lírios",
    slug: "lirios",
    image: cardImage(30),
    keywords: ["paz", "maturidade", "harmonia", "sexualidade", "sabedoria"],
    essence: "A carta busca paz, maturidade, respeito ao tempo e prazer vivido com serenidade.",
    light: "Harmonia, cura, sabedoria, elegância, maturidade e prazer calmo.",
    shadow: "Frieza, lentidão, moralismo, acomodação ou desejo reprimido.",
    advice: "Escolha a via madura e preserve a paz sem negar a verdade.",
    timing: "Lento e maduro; inverno, noite ou longo prazo.",
    yesNo: "Sim",
    areas: {
      geral: "Mostra paz, maturidade, pessoa experiente, conciliação ou assunto de sexualidade serena.",
      amor: "Indica relação madura, carinho tranquilo, intimidade respeitosa ou reconciliação pacífica.",
      sentimentos: "Sentimentos profundos, calmos e respeitosos, com menos pressa e mais presença.",
      trabalho: "Mentoria, experiência, diplomacia, ambiente equilibrado ou resolução madura de conflito.",
      financeiro: "Dinheiro estável, previdência, reserva, decisão conservadora e foco em segurança.",
      energia: "Recuperação por descanso, rotina e serenidade; atenção profissional quando necessário.",
      espiritual: "Paz interior, sabedoria ancestral, purificação e prática meditativa.",
      conselho: "Aja com classe, tempo e respeito; o caminho maduro vence o impulso.",
    },
    combinations: ["Com O Coração mostra amor maduro.", "Com A Árvore reforça cura.", "Com O Chicote pede pacificar tensão repetida."],
  },
  {
    id: 31,
    name: "O Sol",
    slug: "sol",
    image: cardImage(31),
    keywords: ["sucesso", "clareza", "vitalidade", "alegria", "vitória"],
    essence: "A luz revela, aquece e fortalece: há sucesso, clareza, energia e superação.",
    light: "Vitória, confiança, reconhecimento, vitalidade e felicidade.",
    shadow: "Excesso de ego, exposição demais, pressa por aplauso ou queimar energia.",
    advice: "Apareça, confie e use a clareza para agir.",
    timing: "Rápido e luminoso; dia, verão ou fase de visibilidade.",
    yesNo: "Sim",
    areas: {
      geral: "Indica sucesso, clareza, solução, alegria, energia forte e resultado positivo.",
      amor: "Favorece felicidade, reconciliação clara, atração viva e relação que quer aparecer.",
      sentimentos: "Sentimentos positivos, entusiasmo, admiração e vontade de se abrir.",
      trabalho: "Reconhecimento, promoção, bom resultado, liderança e visibilidade profissional.",
      financeiro: "Ganho, melhora, venda bem-sucedida ou clareza para resolver dinheiro.",
      energia: "Vitalidade em alta; cuide para não exagerar por confiança excessiva.",
      espiritual: "Proteção, luz, limpeza, verdade revelada e fortalecimento do campo.",
      conselho: "Escolha o caminho claro, mostre competência e não diminua sua luz.",
    },
    combinations: ["Com A Montanha indica superação de obstáculo.", "Com As Nuvens traz clareza após dúvida.", "Com Os Peixes favorece prosperidade."],
  },
  {
    id: 32,
    name: "A Lua",
    slug: "lua",
    image: cardImage(32),
    keywords: ["intuição", "reconhecimento", "emoção", "imagem", "ciclo"],
    essence: "A carta fala de intuição, sensibilidade, fama, ciclo emocional e imagem pública.",
    light: "Reconhecimento, criatividade, sonho, empatia, magnetismo e percepção.",
    shadow: "Oscilação emocional, fantasia, carência de aprovação ou confusão psíquica.",
    advice: "Escute a intuição, mas confirme com realidade.",
    timing: "Ciclos lunares; cerca de 28 dias ou fases emocionais.",
    yesNo: "Talvez",
    areas: {
      geral: "Mostra intuição, emoções, imagem, reconhecimento, sonhos e ciclo sensível.",
      amor: "Romance, saudade, conexão emocional e necessidade de cuidado com idealização.",
      sentimentos: "Sentimentos profundos, mutáveis e intuitivos, com forte imaginação.",
      trabalho: "Reconhecimento público, arte, cuidado, comunicação emocional e reputação.",
      financeiro: "Ganhos por imagem, público, arte ou serviços sensíveis; cuidado com instabilidade.",
      energia: "Humor, sono e ciclos afetam o bem-estar; procure apoio se houver oscilação intensa.",
      espiritual: "Mediunidade, sonhos, intuição, práticas lunares e sensibilidade energética.",
      conselho: "Dê espaço ao sentir, mas não confunda pressentimento com prova.",
    },
    combinations: ["Com As Estrelas amplia intuição e inspiração.", "Com O Jardim mostra reconhecimento público.", "Com As Nuvens alerta confusão emocional."],
  },
  {
    id: 33,
    name: "A Chave",
    slug: "chave",
    image: cardImage(33),
    keywords: ["solução", "abertura", "certeza", "resposta", "acesso"],
    essence: "A solução existe e pode ser acessada; a carta abre porta, confirma resposta e destrava o tema.",
    light: "Descoberta, segurança, desbloqueio, acerto e resposta importante.",
    shadow: "Achar que uma única chave resolve tudo ou abrir porta sem preparo.",
    advice: "Use a solução encontrada com responsabilidade.",
    timing: "Quando a chave aparece, o destrave costuma ser próximo.",
    yesNo: "Sim",
    areas: {
      geral: "Indica solução, acesso, resposta decisiva, abertura de porta ou ponto-chave da leitura.",
      amor: "Mostra conversa que destrava, pessoa importante ou chave para reconstruir confiança.",
      sentimentos: "Sentimentos ganham clareza e a pessoa entende melhor o que quer.",
      trabalho: "Solução técnica, aprovação, acesso, senha, oportunidade certa ou decisão estratégica.",
      financeiro: "Caminho para resolver dinheiro, aprovação, desbloqueio de recurso ou insight prático.",
      energia: "Encontrar o profissional, método ou rotina certa pode destravar melhora.",
      espiritual: "Chave espiritual, revelação, abertura de caminho e confirmação intuitiva.",
      conselho: "Procure o ponto que destrava todo o resto e aja nele primeiro.",
    },
    combinations: ["Com O Livro revela segredo.", "Com A Montanha abre bloqueio.", "Com O Sol confirma sucesso."],
  },
  {
    id: 34,
    name: "Os Peixes",
    slug: "peixes",
    image: cardImage(34),
    keywords: ["dinheiro", "fluxo", "negócio", "abundância", "independência"],
    essence: "A carta trata de fluxo material, dinheiro, negócios, autonomia e circulação de recursos.",
    light: "Prosperidade, vendas, abundância, liquidez, empreendedorismo e liberdade.",
    shadow: "Dinheiro escapando, ganância, falta de controle ou fluxo emocional instável.",
    advice: "Faça o dinheiro circular com gestão, não por impulso.",
    timing: "Fluxo contínuo; depende de movimento de mercado e decisões.",
    yesNo: "Sim",
    areas: {
      geral: "Mostra dinheiro, negócios, comércio, autonomia, abundância e recursos em movimento.",
      amor: "Pode indicar relação independente, parceiro financeiramente relevante ou amor misturado a dinheiro.",
      sentimentos: "Sentimentos fluem, mas a pessoa valoriza liberdade e espaço.",
      trabalho: "Empreendedorismo, vendas, comissão, mercado, clientes e expansão de receita.",
      financeiro: "Carta central de finanças: fluxo, lucro, investimento, renda e necessidade de gestão.",
      energia: "Hidratação, fluxo corporal e emoções pedem cuidado; não use como diagnóstico.",
      espiritual: "Abundância, merecimento, limpeza por água e fluidez energética.",
      conselho: "Controle entradas e saídas, negocie bem e não deixe abundância virar desperdício.",
    },
    combinations: ["Com O Urso indica grande dinheiro ou investidor.", "Com Os Ratos alerta vazamento financeiro.", "Com O Navio favorece comércio amplo."],
  },
  {
    id: 35,
    name: "A Âncora",
    slug: "ancora",
    image: cardImage(35),
    keywords: ["estabilidade", "trabalho", "fixação", "segurança", "persistência"],
    essence: "A situação busca firmeza, trabalho constante, segurança e permanência.",
    light: "Estabilidade, foco, emprego, confiança, longo prazo e resistência.",
    shadow: "Estagnação, apego, peso, teimosia ou ficar preso por medo.",
    advice: "Firme o que é útil e solte o que virou peso.",
    timing: "Longo prazo; algo durável.",
    yesNo: "Sim",
    areas: {
      geral: "Mostra estabilidade, trabalho, segurança, permanência ou algo difícil de mover.",
      amor: "Indica relação estável, apego forte, compromisso duradouro ou rotina pesada.",
      sentimentos: "Sentimentos firmes e persistentes, mas com tendência a se acomodar.",
      trabalho: "Emprego fixo, carreira, meta de longo prazo, rotina e perseverança.",
      financeiro: "Renda estável, reserva, segurança, investimento conservador ou dinheiro parado.",
      energia: "Rotina sólida ajuda; atenção a rigidez, sedentarismo ou sensação de peso.",
      espiritual: "Aterramento, firmeza, proteção de base e compromisso com prática constante.",
      conselho: "Crie base, mantenha constância e revise o que está te prendendo.",
    },
    combinations: ["Com O Anel reforça compromisso duradouro.", "Com O Chicote indica padrão fixo.", "Com Os Peixes mostra estabilidade financeira."],
  },
  {
    id: 36,
    name: "A Cruz",
    slug: "cruz",
    image: cardImage(36),
    keywords: ["peso", "destino", "fé", "provação", "responsabilidade"],
    essence: "Há um peso espiritual, responsabilidade ou prova que precisa ser atravessada com consciência.",
    light: "Fé, propósito, encerramento kármico, responsabilidade e resistência moral.",
    shadow: "Sofrimento, culpa, fardo, vitimismo, sacrifício excessivo ou obrigação pesada.",
    advice: "Carregue só o que é seu e transforme peso em aprendizado.",
    timing: "Marca fechamento de ciclo, prova longa ou período de responsabilidade.",
    yesNo: "Não",
    areas: {
      geral: "Indica fardo, provação, responsabilidade, destino, fé ou tema que pesa bastante.",
      amor: "Pode mostrar relação sofrida, culpa, apego por dever ou necessidade de encerrar padrão doloroso.",
      sentimentos: "Sentimentos pesados, culpa, dor, compaixão ou sensação de destino inevitável.",
      trabalho: "Carga grande, obrigação, missão difícil, pressão ética ou fim de ciclo profissional.",
      financeiro: "Dívida pesada, obrigação, imposto, sacrifício financeiro ou lição de responsabilidade.",
      energia: "Peso emocional pode afetar vitalidade; busque apoio profissional e rede de cuidado.",
      espiritual: "Fé, karma, oração, encerramento de prova e entrega do que não se controla.",
      conselho: "Não romantize sofrimento; aceite a lição e devolva o fardo que não é seu.",
    },
    combinations: ["Com O Sol mostra superação pela fé.", "Com O Caixão encerra ciclo pesado.", "Com A Âncora indica fardo antigo e fixo."],
  },
];

export const CARD_BY_ID = new Map(LENORMAND_CARDS.map((card) => [card.id, card]));
