import type { DrawMode, TermoPresetConfig, TermoSettings } from "./types";

export const WORD_LENGTH = 5;
export const MIN_TARGETS = 1;
export const MAX_TARGETS = 10;
export const MIN_ATTEMPTS = 5;
export const MAX_ATTEMPTS = 15;

export const TERMO_PRESETS: TermoPresetConfig[] = [
  { id: "termo", label: "Termo", title: "TERMO", targetCount: 1, maxAttempts: 6 },
  { id: "dueto", label: "Dueto", title: "DUETO", targetCount: 2, maxAttempts: 7 },
  { id: "trio", label: "Trio", title: "TRIO", targetCount: 3, maxAttempts: 8 },
  { id: "quarteto", label: "Quarteto", title: "QUARTETO", targetCount: 4, maxAttempts: 9 },
  { id: "custom", label: "Custom", title: "MULTITERMO", targetCount: 5, maxAttempts: 10 },
];

export const DEFAULT_TERMO_SETTINGS: TermoSettings = {
  preset: "termo",
  targetCount: 1,
  maxAttempts: 6,
  wordLength: WORD_LENGTH,
  drawMode: "balanced",
  challengeMode: "random",
};

export const DRAW_MODE_LABELS: Record<DrawMode, string> = {
  balanced: "Balanceado",
  wide: "Aleatorio",
  hard: "Dificil",
};

export const TARGET_COUNT_OPTIONS = Array.from({ length: MAX_TARGETS }, (_, index) => index + 1);
export const ATTEMPT_OPTIONS = Array.from({ length: MAX_ATTEMPTS - MIN_ATTEMPTS + 1 }, (_, index) => MIN_ATTEMPTS + index);

export const KEYBOARD_ROWS = [
  ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P"],
  ["A", "S", "D", "F", "G", "H", "J", "K", "L"],
  ["Z", "X", "C", "V", "B", "N", "M"],
];

export const STORAGE_KEY = "lucasqc-games:termo:v2";

export const CURATED_TARGET_WORDS = [
  "ABRIR",
  "ACHAR",
  "AGORA",
  "ALBUM",
  "ALMAS",
  "ALTAR",
  "ALTOS",
  "AMIGO",
  "AMPLA",
  "AMplo",
  "ANEXO",
  "ANTES",
  "AREIA",
  "ARROZ",
  "ASTRO",
  "ATIVO",
  "ATLAS",
  "AVISO",
  "BAILE",
  "BAIXO",
  "BANCO",
  "BARCO",
  "BARRO",
  "BEIJO",
  "BICHO",
  "BOLSA",
  "BRACO",
  "BRASA",
  "BRISA",
  "BRUTO",
  "BUSCA",
  "CABRA",
  "CAIXA",
  "CALMA",
  "CAMPO",
  "CANAL",
  "CANTO",
  "CAPAZ",
  "CARGA",
  "CARRO",
  "CARTA",
  "CASAL",
  "CASAS",
  "CERCA",
  "CERTO",
  "CHAVE",
  "CHUVA",
  "CINTO",
  "CLARO",
  "CLUBE",
  "COBRA",
  "COFRE",
  "COISA",
  "CONTA",
  "CORAL",
  "CORPO",
  "CORTE",
  "COURO",
  "CRAVO",
  "CRISE",
  "CULPA",
  "DADOS",
  "DANCA",
  "DENTE",
  "DISCO",
  "DOBRA",
  "DUPLA",
  "DURAR",
  "ETAPA",
  "EXATO",
  "FALAR",
  "FALHA",
  "FAROL",
  "FELIZ",
  "FERRO",
  "FESTA",
  "FILHO",
  "FILME",
  "FINAL",
  "FLORA",
  "FOLHA",
  "FORCA",
  "FORMA",
  "FORTE",
  "FOSCO",
  "FRASE",
  "FREIO",
  "FUGIR",
  "FUNDO",
  "GANHO",
  "GARFO",
  "GARRA",
  "GENTE",
  "GIRAR",
  "GOSTO",
  "GRACA",
  "GRADE",
  "GRAMA",
  "GRITO",
  "GRUPO",
  "HOMEM",
  "HORAS",
  "IDEIA",
  "IDOSO",
  "IGUAL",
  "JOGAR",
  "JOGOS",
  "JOVEM",
  "JUNTO",
  "LADOS",
  "LAGOA",
  "LARGO",
  "LENDA",
  "LENTO",
  "LETRA",
  "LINHA",
  "LIVRE",
  "LIVRO",
  "LOJAS",
  "LOUCA",
  "LOUCO",
  "LUGAR",
  "LUZES",
  "MACIO",
  "MAGRO",
  "MALHA",
  "MANGA",
  "MANHA",
  "MANTA",
  "MARCA",
  "MARCO",
  "MARTE",
  "MEIAS",
  "MENOS",
  "MENTE",
  "MESAS",
  "METAL",
  "METRO",
  "MILHO",
  "MINHA",
  "MOEDA",
  "MOLHO",
  "MORAL",
  "MORRO",
  "MORTE",
  "MOTOR",
  "MUNDO",
  "MURAL",
  "NARIZ",
  "NAVIO",
  "NEGRO",
  "NINHO",
  "NOITE",
  "NORTE",
  "NUVEM",
  "OLHAR",
  "ONDAS",
  "OSSOS",
  "OUTRA",
  "OUTRO",
  "PADRE",
  "PAGAR",
  "PALCO",
  "PALHA",
  "PAPEL",
  "PARTE",
  "PASTA",
  "PEDRA",
  "PEIXE",
  "PERTO",
  "PESAR",
  "PILHA",
  "PINHO",
  "PISTA",
  "PLANO",
  "PLENA",
  "PODER",
  "POEMA",
  "PONTE",
  "PONTO",
  "PORCO",
  "PORTA",
  "PRAIA",
  "PRATO",
  "PRECO",
  "PRETO",
  "PROVA",
  "QUASE",
  "QUEDA",
  "RAIVA",
  "RAPAZ",
  "RASTO",
  "REGRA",
  "RELVA",
  "RENDA",
  "RESTO",
  "RISCO",
  "RITMO",
  "RODAS",
  "ROSAS",
  "ROSTO",
  "ROUPA",
  "SABER",
  "SABIO",
  "SAGAZ",
  "SALAO",
  "SALTO",
  "SANTO",
  "SAUDE",
  "SEIVA",
  "SINAL",
  "SOBRA",
  "SOGRA",
  "SONHO",
  "SORTE",
  "SUAVE",
  "SUBIR",
  "TARDE",
  "TEMPO",
  "TENDA",
  "TERRA",
  "TESTE",
  "TIGRE",
  "TINTA",
  "TOCAR",
  "TOMAR",
  "TORRE",
  "TRAMA",
  "TREVO",
  "TRIGO",
  "TROCA",
  "TURMA",
  "UNIAO",
  "VAGAO",
  "VALES",
  "VALOR",
  "VAZIO",
  "VELHO",
  "VENTO",
  "VERDE",
  "VIDRO",
  "VINHO",
  "VIRAR",
  "VISAO",
  "VISTA",
  "VIVER",
  "VOZES",
];
